# Generated by Django 2.2.3 on 2020-02-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_completed', models.DateField(blank=True, default=None, null=True)),
                ('date_last_load', models.DateField(auto_now_add=True)),
                ('bricks_at_the_moment', models.IntegerField(default=0)),
                ('total_bricks_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brick_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bricks', models.IntegerField()),
                ('date_load', models.DateField()),
                ('excessive_bricks', models.IntegerField(default=0)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bricks_api.House')),
            ],
        ),
    ]
