# Generated by Django 2.2.3 on 2020-02-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_api', '0002_auto_20200215_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick_task',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brick_tasks', to='bricks_api.House'),
        ),
    ]
